### ISSUE TITLE
Abilitiy to increase delay timout

### ISSUE THREAD

**Issue by aryanneacosta** [lejara/BattleOfTheChat#1]
It would be a great feature for small streamers to adjust the delay timeout. We faced some issues while playing due to the delay and if the streamer could manually adjust it, it would be better to play. Even if it was a small adjustment, like choosing between two values.

**Comment by lejara** [comment]
Hello!

Thank you for your feedback~!

Fun fact,
I was thinking the same thing
I like the idea. Gonna add it!


Luckily i wrote code for a number input during development. Its just buried in commits.
So this should be done in a few minutes. ill push a update soon

**Comment by lejara** [comment]
also i am assuming your talking about the stream delay timer

**Comment by lejara** [comment]
Added
